name: CMake-Linux64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependancies
      run: |
        sudo apt update
        sudo apt install gcc
        sudo apt install libogg-dev
        sudo apt install libsdl2-dev
        sudo apt install libsdl2-ttf-dev
        sudo apt install libsdl2-image-dev
        sudo apt install zlib1g-dev
        sudo apt install libvorbis-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../src
        make
    - uses: actions/upload-artifact@v3
      with:
        name: hypseus
        path: build/hypseus
